CREATE TABLE CUSTOM_RULE (
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    REQ_URI varchar(2000) NOT NULL,
    RESP_STATUS_CODE INT,
    RESP_CONTENT_TYPE varchar(200),
    RESP_BODY varchar(5000),
    CREATE_AT varchar(100) NOT NULL
);

CREATE UNIQUE INDEX IDX_CUSTOM_REQUEST_URI ON CUSTOM_RULE (REQ_URI);
CREATE INDEX IDX_CUSTOM_CREATE_AT ON CUSTOM_RULE (CREATE_AT);