spring:
  application:
    name: mock-http-backend
  profiles:
    include: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/mock-http.db
    username:
    password:
    druid:
      filters: stat
      maxActive: 200
      initialSize: 2
      maxWait: 5000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
#      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      web-stat-filter:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
      WRITE_BIGDECIMAL_AS_PLAIN: true

server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      pattern: common
      prefix: undertow.access.
      rotate: true
      suffix: log

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics, configprops, env, scheduledtasks
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
